# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build File
        run: |
          chmod +x gradlew 
          ./gradlew build

      - name: Upload File
        uses: actions/upload-artifact@v3
        with:
          name: HeliosClient
          path: build/libs

      - name: Discord Notification
        uses: appleboy/discord-action@master
        if: ${{ success() }}
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: 3066993
          title: "Build Successful"
          description: "The build of the project was successful. Here are some details..."
          fields: '[{"name": "Branch", "value": "${{ github.ref }}", "inline": true}, {"name": "Commit", "value": "${{ github.sha }}", "inline": true}]'
